name = "HJB"
uuid = "a3cb4e6c-25e7-429f-8c59-1a4059c3ba7b"
authors = ["Devansh Ramgopal Agrawal <devansh@umich.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
